/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Quantum Egg": "量子蛋",
    "Reach Rocket Fuel Eggs": "到达火箭燃料蛋",
    "Reduce Research Costs by 5%": "将研究成本降低 5%",
    "Regular Egg": "普通蛋",
    "Relativity Optimization": "相对论优化",
    "Research": "研究",
    "Rocket Fuel Egg": "火箭燃料蛋",
    "Save Game": "保存游戏",
    "Shell Fortification": "外壳防御工事",
    "Soul and Prophecy Eggs will lose their effects": "灵魂蛋和预言蛋将失去效果",
    "Soul Food": "灵魂食物",
    "Start with 1 Chicken": "从 1 只鸡开始",
    "Start with 1 Chicken on any Reset": "在任何重置时从 1 只鸡开始",
    "Stats": "统计",
    "Submit": "提交",
    "Super Material Egg": "超级材料蛋",
    "Super-Feed™ Diet": "超级饲料™ 饮食",
    "Superfood Egg": "超级食物鸡蛋",
    "Tachyon Egg": "超光速蛋",
    "Telepathic Will": "心灵感应意志",
    "Terraform Egg": "地球化蛋",
    "Thanks!": "谢谢！",
    "the contract is complete or cancelled!": "合同完成或取消！",
    "There is 50% chance for the egg to be a dinosaur egg: it either is or is not": "鸡蛋有 50% 的几率是恐龙蛋：要么是，要么不是",
    "Time Compression": "时间压缩",
    "Time Played (Includes Time Away): 0": "上场时间（包括离开时间）：0",
    "Timeline Diversion": "时间线转移",
    "Timeline Splicing": "时间线拼接",
    "To Pursue Enlightenment one must give up everything.": "要追求启蒙，必须放弃一切。",
    "Triples Egg Value": "三倍鸡蛋价值",
    "Universe Egg": "宇宙蛋",
    "Unlock at Fusion Eggs": "解锁于 融合蛋",
    "USDE Prime Certification": "USDE初级认证",
    "Last 3 Prestiges": "最近3次声望",
    "Enlightenments": "启蒙",
    "Credits": "鸣谢",
    "Crystalline Shelling": "结晶脱壳",
    "Regular": "常规",
    "Current Version - v1.1.1": "当前版本 - v1.1.1",
    "Darkmatter Egg": "暗物质蛋",
    "Delete Save (Exports)": "删除保存（导出）",
    "Dilithium Egg": "双锂蛋",
    "Discord Link!": "Discord链接！",
    "Discover Planet": "探索星球",
    "Discover Planet: Cost 50 Million Rocket Fuel Eggs": "探索星球：花费 50 M 火箭燃料蛋",
    "Discovered Eggs": "发现的鸡蛋",
    "Double Egg Density (Value)": "双倍鸡蛋密度（价值）",
    "Doubles Egg Value": "鸡蛋价值翻倍",
    "Earnings Per Egg +25%": "每个鸡蛋的收益 +25%",
    " & Egg Value + 15%": " & 鸡蛋价值 + 15%",
    "Egg Quality (Value) +25%": "鸡蛋质量（价值）+25%",
    "Eggcellent Unlocked!": "鸡蛋仔 已解锁！",
    "Eggs": "蛋",
    "Eggsistor Miniturization": "蛋奶器小型化",
    "Eggspeditions": "鸡蛋探险",
    "Enter the Path": "输入路径",
    "Epic Comfy Nests": "史诗般的舒适巢穴",
    "Epic Internal Hatcheries": "史诗内部孵化场",
    "Error NAN Display Fix, New Formatter, Auto Save is 30s Interval Now (Originally 10s), Stats Screen, Achievements": "Error NAN Display Fix, New Formatter, Auto Save is 30s Interval Now (Original 10s), Stats Screen, Achievements",
    "Even Bigger Eggs": "更大的鸡蛋",
    "Export Save": "导出存档",
    "Fusion Egg": "融合蛋",
    "Gapples2": "间隙2",
    "Gazyn": "加赞",
    "Genetic Purification": "基因纯化",
    "Github Repo!": "Github 仓库！",
    "Go on an Eggspedition": "进行一次鸡蛋探险",
    "Graviton Coating": "引力子涂层",
    "Graviton Egg": "重力蛋",
    "Hen House A/C": "母鸡屋空调",
    "Hover over a planet to see what it is": "悬停在一个星球上，看看它是什么",
    "Hover Over An Image to See Its Description": "将鼠标悬停在图像上以查看其描述",
    "Immortality Egg": "永生蛋",
    "Import Save": "导入保存",
    "Improved Genetics": "改进的遗传学",
    "Increase Chicken Gain by 5%": "增加鸡增益 5%",
    "Increase Egg Value by 5%": "鸡蛋价值增加 5%",
    "Increase Soul Egg Bonus by 1%": "增加魂蛋奖励 1%",
    "Increases Egg Value +1%": "增加鸡蛋价值 1%",
    "Internal Hatcheries": "内部孵化场",
    "Internal Hatchery Expansion": "内部孵化场扩建",
    "Internal Hatchery Upgrades": "内部孵化场升级",
    "Lab Upgrade": "实验室升级",
    "10x Egg Value": "10x 鸡蛋价值",
    "!Warning! - Journeying to any planet will cause a reset on the main farm.": "！警告！ - 前往任何星球都会导致主农场重置。",
    "!When you start a contract you will do a prestige reset and be unable to leave the egg until": "!当你开始一个合同你会做一个声望重置并且不能离开鸡蛋直到",
    "[MAJOR UPDATE]": "[主要更新]",
    "A Californian Energy Shortage means more demand for Fusion Eggs": "加州能源短缺意味着对融合蛋的需求增加",
    "Accept": "接受",
    "Accounting Tricks": "会计技巧",
    "AI Egg": "人工智能蛋",
    "All Research Bonuses Compound": "所有研究奖金复合",
    "Alpha Versions": "阿尔法版本",
    "Antimatter Egg": "反物质蛋",
    "Are you sure?": "你确定吗？",
    "Atomic Purification": "原子净化",
    "Automate Tier I-V Research": "自动化 Tier I-V 研究",
    "Automate Tier VI-X Research": "自动化 Tier VI-X 研究",
    "Automated Tier XI-XIV Research": "自动化第 XI-XIV 层研究",
    "Automatic Promotions": "自动进阶",
    "Best Egg: Regular": "最好的鸡蛋：普通",
    "Bigger Eggs": "更大的鸡蛋",
    "Click to Hatch +1 Chicken": "点击孵化+1鸡",
    "Comfortable Nests": "舒适的窝",
    "Contracts": "合同",
    "DONT EAT SCRAMBLED NEBULA EGGS!!! They taste terrible…": "不要吃炒星云蛋！！！它们尝起来很糟糕……",
    "Egg": "蛋",
    "Egg is the next mechanic": "蛋 是下一个技工",
    "eggineer gaming": "蛋蛋游戏",
    "eggs! get your eggs here!": "蛋！把你的鸡蛋拿过来！",
    "Game Loaded": "游戏加载",
    "Game Saved": "游戏已保存",
    "I don't think this will meet FDA standards.": "我认为这不会符合 FDA 标准。",
    "I heard that there's a secret prophecy egg stash at https://discord.gg/kFYgun8Yqs": "我听说在 https://discord.gg/kFYgun8Yqs 有一个秘密的预言蛋藏匿处",
    "It takes 3000 grains to produce an egg": "生产一个鸡蛋需要3000粒谷物",
    "Machine Learning Incubators": "机器学习孵化器",
    "Matter Reconfiguration": "物质重构",
    "Medical Egg": "医用鸡蛋",
    "Multiversal Layering": "多重分层",
    "Nebula Egg": "星云蛋",
    "Neural Linking": "神经链接",
    "New things have been added since last time": "自上次以来已添加新内容",
    "NEWS BREAKING: EGG INC WILL RISE AGAIN, YOU CAN NOT STOP US. WEghuiuofvjbsvuiosrfb Apologies for that, there's been a break in at the office. Have a good day.": "新闻快讯：EGG INC 将再次崛起，您无法阻止我们。 WEghuiuofvjbsvuiosrfb 抱歉，办公室有人闯入。祝你有美好的一天。",
    "Not Discovered": "未发现",
    "Superfood": "超级食品",
    "No!": "不！",
    "Nutritional Supplements": "营养补充剂",
    "Other Prestige Stats": "其他声望统计",
    "Padded Packaging": "填充包装",
    "Prestige": "声望",
    "Prestige Bonus": "声望奖励",
    "Prodigy Egg": "神童蛋",
    "Programmers": "程序员",
    "Promote to Next Egg": "进阶到下一个蛋",
    "Promotion": "进阶",
    "Off": "关闭",
    "Public Release": "公开发布",
    "That sounds like a skill issue": "感觉是技能问题",
    "This game takes only a few moments to beat if you know how to use the console.": "如果您知道如何使用控制台，则只需几分钟即可完成此游戏。",
    "This is the game, egg inc. is the copy.": "这是游戏，鸡蛋公司。是一个副本。",
    "VoidCloud": "虚云",
    "Welcome back gamer!": "欢迎回来游戏玩家！",
    "Welcome Back!": "欢迎回来！",
    "Yes!": "是的！",
    "You will be unable to prestige as well as you will be unable to leave the enlightenment egg.": "您将无法获得声望，也将无法离开启蒙蛋。",
    "which came first, the egg or the egg?": "先有蛋还是先有蛋？",
    "Cluck Cluck": "咯咯哒咯咯哒",
    "Egg prices have dropped due to this one guy having one million chickens WTF!": "因为这个人有一百万只鸡WTF，鸡蛋价格下降了！",
    "Florida man has broken several walls, the costs are too expensive to fix! (idk)": "佛罗里达人破了几堵墙，修起来太贵了！ （身份证）",
    "New Coop Co update! Changelog 420.69: Added 4,736th egg along with new prestige, Going Outside! This prestige will reset the game and give you no boosts!": "新的合作公司更新！ 更新日志 420.69：添加了第 4,736 个鸡蛋以及新的声望，Going Outside！ 这个声望会重置游戏并且不会给你任何提升！",
    "not using scientific notation, laugh at this user": "不使用科学计数法，嘲笑这个用户",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "BREAKING NEWS: Florida Man eats rocket fuel egg": "突发新闻：佛罗里达男子吃火箭燃料蛋",
    "Dimava": "Dimava",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Tier ": "层级 ",
    "Research-": "研究-",
    "Time in Current Prestige: ": "本轮声望耗时：",
    "Current Egg: ": "当前的蛋：",
    "Knowledge: ": "知识：",
    "Enlightenment ": "启蒙 ",
    "Egg Value +": "鸡蛋价值 +",
    "Egg Laying Rate": "产蛋率",
    "Current Egg: ": "当前鸡蛋：",
    "Best Money: $": "最佳资金：$",
    "Chickens: ": "鸡：",
    "Changelog :": "更新日志：",
    "Contract-": "合同-",
    "Promotion Auto: ": "自动推广：",
    "Prophecy Eggs: ": "预言蛋：",
    "Buy Amount: ": "购买数量：",
    "Chicken Gain: ": "鸡增益：",
    "Next Egg: ": "下一个蛋：",
    "Best Chickens: ": "最佳的鸡：",
    "Best Prophecy Eggs: ": "最佳预言蛋：",
    "Best Soul Eggs: ": "最佳魂蛋：",
    "Contracts Completed: ": "完成的合同：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " Automator": " 自动机",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You were gone for (.+) seconds$/, '你离开了 $1 秒'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Hey, congrats on (.+)$/, '嘿，恭喜您获得 $1！'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) Chickens\/min$/, '$1 鸡\/分钟'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Chickens\/min$/, '\+$1 鸡\/分钟'],
    [/^\+([\d\.,]+)\% More Soul Eggs per Prestige$/, '每次声望 \+$1\% 魂蛋'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Reward: (.+) Soul Eggs$/, '奖励：$1 点数'],
    [/^Prestige (.+): (.+) Soul Eggs$/, '声望 $1：$2 魂蛋'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Soul Eggs$/, '成本：$1 魂蛋'],
    [/^Value: \$([\d\.]+)$/, '价值：\$$1'],
    [/^Cost: \$([\d\.]+)$/, '成本：\$$1'],
    [/^Cost: \$([\d\.]+) (.+)$/, '成本：\$$1 $2'],
    [/^Value: \$([\d\.]+) (.+)$/, '价值：\$$1 $2'],
    [/^Soul Eggs: (.+)$/, '魂蛋：$1'],
    [/^Unlock At: (.+)$/, '解锁于：$1'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Level: (.+)\/(.+)$/, '等级：$1\/$2'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);